name: First Workflow 

on: push 

jobs:
    first_job:
        runs-on: ubuntu-latest 
        steps:
            - name: welcome
              run: echo "My firsrt GitHub Actions Pipeline"

            - name: List files 
              run: ls 
            
            - name: read file readme.md 
              run: cat README.md
              